### ISSUE TITLE
wrong class for private key when signing transaction

### ISSUE THREAD

**Issue by christian-trummer** [blockcypher/php-client#1]
i am using blockcypher to sign transactions locally. it works fine and doesnt throw an exception when i use the sample code of CreateAndSignAndSendTransaction.php also the transaction gets send but i do get the following PHP error!

PHP Error: 4096 - Argument 1 passed to BlockCypher\Crypto\PrivateKeyList::addPrivateKey() must be an instance of BitWasp\Bitcoin\Key\PrivateKeyInterface, instance of BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PrivateKey given, called in XXX\vendor\blockcypher\php-client\lib\BlockCypher\Crypto\PrivateKeyList.php on line 42 and defined

i habe passed an hex private key.

**Comment by christian-trummer** [comment]
looks like BitWasp has changed something in their interface

**Comment by josecelano** [comment]
hi @christian-trummer It seems [BitWasp/bitocin-php](https://github.com/Bit-Wasp/bitcoin-php) library has been refactored. Our composer.json is configured to upgrade only minor versions (0.0.*)  but in this case even new minor versions break the API. I am going to fix the composer to require only 0.0.7 which is the last version which works fine. I wil try to release the new version asap.

**Comment by josecelano** [comment]
hi @christian-trummer I have released v1.2.2. You should not get that error with this new version. Is there anything else I can do for you? Please, let me know if I can close the issue.

**Comment by christian-trummer** [comment]
thank you. everything is working fine now!
