### ISSUE TITLE
problem in running the CreateAndSignAndSendTransaction.php file

### ISSUE THREAD

**Issue by alielectric** [blockcypher/php-client#108]
hi there i wanna create and sign and send a simple transaction but i encountered to a simple problem. i just try to run the sample code but it has problems what should i do?
the error is below:
Fatal error: Uncaught TypeError: Argument 1 passed to BlockCypher\Crypto\PrivateKeyList::addPrivateKey() must be an instance of BitWasp\Bitcoin\Key\PrivateKeyInterface, instance of BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PrivateKey

**Comment by quentinlesceller** [comment]
This is fixed in #111.
