### ISSUE TITLE
Error: Not Enough Funds

### ISSUE THREAD

**Issue by GhoSTBG** [blockcypher/php-client#109]
Hi guys,
I'm using the CreateTransaction API. Everything works as expected, but my minimum fee to send a transaction from newely generated address is 13,500 satoshies, which is near 72 sat / B.

JSON Here: [click](https://jsoneditoronline.org/#left=cloud.2603f608b7594512a328bf776043b4d2)

**Comment by quentinlesceller** [comment]
You can lower the preference to pay lower fees.
