### ISSUE TITLE
Argument 1 passed to BlockCypher\Rest\ApiContext::setConfig() must be of the type array

### ISSUE THREAD

**Issue by vanderjelly** [blockcypher/php-client#112]
**Hello**

_step to reproduce_

1: installation from composer 

> composer require "blockcypher/php-client:*"

2: trying to use the basic tutorial present in your home page.
```php
    $token = 'c0afcccdde5081d6429de37d16166ead';
    $config = array(
        'mode' => 'sandbox',
        'log.LogEnabled' => true,
        'log.FileName' => 'BlockCypher.log',
        'log.LogLevel' => 'DEBUG', 
        'validation.level' => 'log',
    );

    $apiContext = ApiContext::create(
        'main', 'btc', 'v1',
        new SimpleTokenCredential('c0afcccdde5081d6429de37d16166ead'),
        $config
    );

$addressClient = new AddressClient($apiContext);
$address = $addressClient->get('1DEP8i3QJCsomS4BSMY2RpU1upv62aGvhD');

echo "JSON Address: " . $address->toJson() . "\n";
var_dump($address);
```
3: After copying all code of the home page i got this error : 

> Argument 1 passed to BlockCypher\Rest\ApiContext::setConfig() must be of the type array

_What i'm using ?_

- php7.3 with required extension provided in your home page.
- linux on fedora 31.
- laravel 7

I have trying to search on stackoverflow for exemple an topic have the same error but for paypal, i have try to solve my problem with thes topic answer, but i still got the same error
______

One week ago i have got an error on trying to install this package on laravel 7 but one of your repository like switch them public to private if that can help us.

______

**Edit**

that is the same for the code in the blockcypher documentation : [BlockCypher Doc](https://www.blockcypher.com/dev/bitcoin/?php#documentation-structure)
> PHP and the code that i copy :

```php

$apiContext = ApiContext::create(
        'main', 'btc', 'v1',
        new SimpleTokenCredential('my token'),
        array('log.LogEnabled' => true, 'log.FileName' => 'BlockCypher.log', 'log.LogLevel' => 'DEBUG')
    );
    dd($apiContext);

```

**Comment by vanderjelly** [comment]
Solving with these code

```php

$apiContext = ApiContext::create(
        new SimpleTokenCredential('YOUR_TOKEN'), array('log.LogEnabled' => true, 'log.FileName' => 'BlockCypher.log', 'log.LogLevel' => 'DEBUG'), 'v1'
    );
    dd($apiContext);

```

**Comment by judikaelB** [comment]
Don't miss to add in the array for config
> 'mode' => 'sandbox',

**Comment by quentinlesceller** [comment]
@vanderjelly and @judikaelB can you confirm that the following code works?
```php
$apiContext = ApiContext::create(
        new SimpleTokenCredential('YOUR_TOKEN'), array('mode' => 'sandbox', 'log.LogEnabled' => true, 'log.FileName' => 'BlockCypher.log', 'log.LogLevel' => 'DEBUG'), 'v1'
    );
    dd($apiContext);
```

If yes I will update the example. Many thanks for your contribution.

**Comment by vanderjelly** [comment]
Yes this work very well :) But Many class like multisig are not present what will replace it ?

**Comment by quentinlesceller** [comment]
What do you mean? Does this example still works https://github.com/blockcypher/php-client/blob/a7e7caa3de474d976a0c3bdeb136354016b141ea/sample/doc/address-api/CreateMultisigAddress.html ?

**Comment by vanderjelly** [comment]
I have don't try your link but this:

```php
$addressClient = new AddressClient($apiContext);
$pubkeys = array(
    "02c716d071a76cbf0d29c29cacfec76e0ef8116b37389fb7a3e76d6d32cf59f4d3",
    "033ef4d5165637d99b673bcdbb7ead359cee6afd7aaf78d3da9d2392ee4102c8ea",
    "022b8934cc41e76cb4286b9f3ed57e2d27798395b04dd23711981a77dc216df8ca"
);
$addressKeyChain = $addressClient->generateMultisigAddress($pubkeys, 'multisig-2-of-3');

{
  "pubkeys":[
    "02c716d071a76cbf0d29c29cacfec76e0ef8116b37389fb7a3e76d6d32cf59f4d3",
    "033ef4d5165637d99b673bcdbb7ead359cee6afd7aaf78d3da9d2392ee4102c8ea",
    "022b8934cc41e76cb4286b9f3ed57e2d27798395b04dd23711981a77dc216df8ca"
  ],
  "script_type":"multisig-2-of-3",
  "private":"",
  "public":"",
  "address":"3BF1M1PnTge94QewuWh3B8mRVw8U4SVnb4",
  "wif":""
}

```

that code is enable to see in the doc of [BlockCypher](https://www.blockcypher.com/dev/bitcoin/#generate-multisig-address-endpoint)

The class Address Client does not exist and the method generateMultisigWallet does not work from Address class

**Comment by quentinlesceller** [comment]
Okay I’ll take a look. Let me know if you manage to do it. Seems like the transition to php 7 was not super smooth then. The php 4 branch is very stable but very old if you need something production ready.

**Comment by vanderjelly** [comment]
Ok i know but i'm integrating this package on my framework laravel 7, them use php 7.2 at minimum php requirement.

I think your repository was updated from 3 month and some class don't work today for the actual BlockCypher PHP Doc.
