### ISSUE TITLE
Confidence property type in BlockCypher\Api\TX might be wrong

### ISSUE THREAD

**Issue by rtarnaud** [blockcypher/php-client#15]
Hello Jose,

When calling the 'get' method of the TXClient to retrieve info about a transaction, you get a Tx object as the return value of 'get'. However the confidence property of Tx is of type 'int' according to the phpdoc lines of TX.php. Should not it be 'float' or maybe 'string' as it is a real number comprised between 0 and 1? (btw, that's what you get if you call the webservice directly by curl).

Edit: The 'get' method of TXClient only allows instart, outstart, limit, includeHex as optional parameters but not includeConfidence which is the one I am interested in (this one actually populates the json response with the confidence field). This might explain my problem.

Thx

**Comment by josecelano** [comment]
Hi @rtarnaud , yes you are rigth that property should be `float` in phpdoc. Anyway It should return a `float` if the json response is a float number. I have changed the phpdoc.

The latest release: https://github.com/blockcypher/php-client/releases/tag/v1.3.0
have been changed to allow the new  `includeConfidence` parameter in `TXCLient::Get` method:

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Client/TXClient.php#L56

You can upgrade to that release or you can change validation level to `log` or `disabled` and the `TXClient::get` will acept that parameter even if you do not upgrade.

I have also added a sample of `TXClient::get` using the `confidenceFactor` param:

https://github.com/blockcypher/php-client/blob/master/sample/transaction-api/GetTransactionWithConfidenceFactor.php#L13

```
$transaction = $txClient->get('f854aebae9515...166f58bd5063449', array('includeConfidence' => 'true'));
```

**Comment by rtarnaud** [comment]
That's perfect, thanks again!

**Comment by josecelano** [comment]
You're welcome. Thanks for your feedback.
