### ISSUE TITLE
Segfault caused by CURLOPT_HTTPHEADER => array()

### ISSUE THREAD

**Issue by binarystorm** [blockcypher/php-client#16]
As described here [https://bugs.php.net/bug.php?id=71703](https://bugs.php.net/bug.php?id=71703) the assignment of an empty array to CURLOPT_HTTPHEADER in BlockcypherHttpConfig.php can lead to a segfault.

**Comment by josecelano** [comment]
Thank you @binarystorm and sorry for the delay. I have fixed and soon I will release version v1.3.1.
