### ISSUE TITLE
Unable to send transaction problem with Mdanter\Ecc\Math\Gmp IN bitwasp\bitcoin

### ISSUE THREAD

**Issue by emabusi** [blockcypher/php-client#22]
I have just setup the client and after following the sample code I get the error below

Class 'Mdanter\Ecc\Math\Gmp' not found in C:\xampp\htdocs\cck\vendor\bitwasp\bitcoin\src\Math\Math.php on line 8

I checked file the vendor and there is Gmp file or class in Mdanter\Ecc\Math\Gmp, so i edited the math.php file and edited line 6 to use \Mdanter\Ecc\Math\GmpMath as Gmp; and now get the error like the one in https://github.com/blockcypher/php-client/issues/21

**Comment by josecelano** [comment]
Hi @emabusi I think it's the same problem as issue #21. I think the library `bitwasp/bitcoin` version `0.0.7` can not user higer versions than `0.3.1` for library `mdanter/ecc` so it seems to be a dependency problem between those libraries. For me it works with:

```
PHP 5.4.4,
"mdanter/ecc": "0.3.0",
"bitwasp/bitcoin": "v0.0.7"
```

Try to put this explicit dependency in your app:
"mdanter/ecc": "0.3.0",
and if that works we can open an issue in `bitwasp/bitcoin` library.

**Comment by josecelano** [comment]
Hey @emabusi try to run:

```
composer update blockcypher/php-client
```

to update `blockcypher/php-client` to latgest version `v1.5.0`. The problem with dependencies should be fixed.

**Comment by emabusi** [comment]
for reference this issue was solved as shown https://github.com/blockcypher/php-client/issues/21

**Comment by InspiredPrynce** [comment]
None of this things seem to work for me at the moment...

"blockcypher/php-client": "^1.5",

"name": "mdanter/ecc",
"version": "v0.5.0",
"source": {
"type": "git",
"url": "https://github.com/phpecc/phpecc.git",
"reference": "ed5c6d496f5310de1b7071b8375fafa3559a1344"
},

"name": "bitwasp/bitcoin",
"version": "v0.0.7",
"source": {
"type": "git",
"url": "https://github.com/Bit-Wasp/bitcoin-php.git",
"reference": "7316b7bc5fc204d972e5df3b2485366ee4cd1a18"
},

Help me please
