### ISSUE TITLE
Problem with create transaction

### ISSUE THREAD

**Issue by hakerkiler** [blockcypher/php-client#32]
Hi. I work with your https://www.blockcypher.com/dev/dash/#creating-transactions API

In this pack I not found \BlockCypher\Api\Output , \BlockCypher\Api\Input this two fail and i can't create transaction

Need your help please

Thanks

**Comment by menriquez** [comment]
hi...i was getting ready to start using this API and was wondering if you every solved this issue and if so, how?  

i certainly do not want to begin development with an API that has issues with transactions...

thanks

**Comment by josecelano** [comment]
Sorry @hakerkiler @menriquez I am the only mantainer of this package and I have been very busy. I would try to check it asap. 

@hakerkiler I think your problem could be that the documentation is outdated and those classes were renamed in newer versions. You can find a lot of samples in this folder:
https://github.com/blockcypher/php-client/blob/master/sample/transaction-api/CreateTransactionToFundMultisigAddress.php
Sorry for that, I would try to update docs also asap.

And @menriquez this package is only a PHP wrapper for the REST API which is very robust, if you are going to use only a couple of different requests you can implement your own helper classes. This package contains some builders/helpers to make easier to build requests for the REST API.

**Comment by menriquez** [comment]
hey @josecelano ...awesome thanks for the quick reply..\gotcha about the wrapper...i am sure id have little problem building my own if I find issues.

I look forward to beginning work with this and am very heartened by the fact you are "lurking around" keeping an eye on things. 

regards
- mark

**Comment by hakerkiler** [comment]
One more question
`[2017-08-12 20:37:28] local.INFO: HTTP/1.1 400 Bad Request
Server: nginx/1.11.10
Date: Sat, 12 Aug 2017 20:37:28 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods: GET, POST, PUT, DELETE
Access-Control-Allow-Origin: *
X-Ratelimit-Remaining: 183

{
  "errors": [
    {
      "error": "Not enough funds after fees in 8 inputs to pay for 1 outputs, missing -185035."
    }
  ],
  "tx": {
    "block_height": -1,
    "block_index": -1,
    "hash": "6c002d79120e0e2636c0e60ff41c98197f912543a3b60ef8df420b3aa8049e04",
    "addresses": [
      "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr",
      "XydqugdWcn87ciCe3YvraikuhAcWvBRKar"
    ],
    "total": 4000,
    "fees": 93765,
    "size": 372,
    "preference": "high",
    "relayed_by": "5.188.234.155",
    "received": "2017-08-12T20:37:28.644769472Z",
    "ver": 1,
    "lock_time": 0,
    "double_spend": false,
    "vin_sz": 8,
    "vout_sz": 1,
    "confirmations": 0,
    "inputs": [
      {
        "prev_hash": "354062a5be9a692b37869684f48167ee91b30fb0562b94c3d146b5b397794b18",
        "output_index": 1,
        "script": "",
        "output_value": 26464,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "05a022e57944f78150c70b6a2bc7182ff3ce02a73571d9227f481e0a828be230",
        "output_index": 1,
        "script": "",
        "output_value": 30696,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "2fe1e1cfd739ac695d2904226ce7286b8f340b39e804806767aff6da06a19e96",
        "output_index": 0,
        "script": "",
        "output_value": 7321,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "d40d3f1effb7655a7b9c85226af1f9646ec5ea0f4a13c7b9090ec6ffefbf2fb2",
        "output_index": 0,
        "script": "",
        "output_value": 7321,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "2d848d5e90d93f935e4386d2ba62f3798babfc8c3d12a3274ce295cef49ce535",
        "output_index": 0,
        "script": "",
        "output_value": 7321,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "d7789a21d23f2f034b19dfbc44b3ac9334844e3c25fc6e126d01efc7940a3b76",
        "output_index": 0,
        "script": "",
        "output_value": 7321,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "55446bb2cf943dcda487e3a48894cb45749d4136ec2dac58d4102a5caaad0f61",
        "output_index": 0,
        "script": "",
        "output_value": 7321,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      },
      {
        "prev_hash": "21f875227f718b21cf05b4aa50f8f8fbb8e0ce8a33eb71b688c6802173d7dd9e",
        "output_index": 0,
        "script": "",
        "output_value": 4000,
        "sequence": 4294967295,
        "addresses": [
          "Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr"
        ],
        "script_type": ""
      }
    ],
    "outputs": [
      {
        "value": 4000,
        "script": "76a914fbb9b57b0aab5fa225a8d3a2e105c5b8180f2dc388ac",
        "addresses": [
          "XydqugdWcn87ciCe3YvraikuhAcWvBRKar"
        ],
        "script_type": "pay-to-pubkey-hash"
      }
    ]
  },`

wallet balance https://api.blockcypher.com/v1/dash/main/addrs/Xe44rrZS2krX9jimYQ8psDwkBrtgLyG1yr
