### ISSUE TITLE
API/Webhook Lacking confirmations Getter/Setter. Plus its unfair to limmit API access for developers

### ISSUE THREAD

**Issue by ofumbi** [blockcypher/php-client#33]
This error shows up when trying to setup a web-hook, and honestly 200 calls an hour are to little when trying top develop a wallet.( I have to wait just to test and debug an issue, your api has realy wasted my working time. I only wish I had advised the client to host his own blockchains, wont be taking jobs to anymore to develop any apps on your platform for I have never seen any service that bills developers to integrate their service for clients !!!)

**Comment by matthieu** [comment]
Frankly, 200 calls an hour has been enough for the great majority or developers we've seen. And we have to still be able to monetize once people go to later stages.
