### ISSUE TITLE
Am having issues creating transaction and sending it to the network

### ISSUE THREAD

**Issue by nwa070** [blockcypher/php-client#34]
Please help me out, i can create address and i can get address balance but my problem now i can not create transaction, even when i tried to use btc test net it still not working, but when i try the default sample source code, the code works fine both in btctest net and and sample code. 
These are the error i keep on getting 
"Got Http response code 400 when accessing https://api.blockcypher.com/v1/bcy/test/txs/new?token="

{
    "errors": [
        {
            "error": "Unable to find a transaction to spend for address 1JHMjL7V3heBZYieNcyHaqvy2aPA5fmY7S."
        },
        {
            "error": "Error building transaction: Invalid output address: wrong network.."
        },
        {
            "error": "Not enough funds after fees in 0 inputs to pay for 0 outputs, missing -14200."
        },
        {
            "error": "Error validating generated transaction: Transaction missing input or output."
        }
    ],
    "tx": {
        "block_height": -1,
        "block_index": -1,
        "hash": "d21633ba23f70118185227be58a63527675641ad37967e2aa461559f577aec43",
        "addresses": [],
        "total": 0,
        "fees": 0,
        "size": 10,
        "preference": "low",
        "relayed_by": "178.33.235.187",
        "received": "2017-07-04T18:46:17.299499716Z",
        "ver": 1,
        "lock_time": 0,
        "double_spend": false,
        "vin_sz": 0,
        "vout_sz": 0,
        "confirmations": 0,
        "inputs": [],
        "outputs": []
    }
}

when i check the log file 
this is what i see

[29-06-2017 09:08:53] BlockCypher\Validation\ModelAccessorValidator: DEBUG	: Missing Accessor: BlockCypher\Api\TX:setBlockIndex. You might be using older version of SDK. If not, create an issue at https://github.com/blockcypher/php-client/issues
[29-06-2017 09:08:53] BlockCypher\Validation\ModelAccessorValidator: DEBUG	: Missing Accessor: BlockCypher\Api\TX:setBlockIndex. You might be using older version of SDK. If not, create an issue at https://github.com/blockcypher/php-client/issues

please help me the createTransaction.php and CreateAndSignAndSendTransaction.php error has kept me in a box since 4months till now.

**Comment by josecelano** [comment]
Hi, that API enpoint  `https://api.blockcypher.com/v1/bcy/test/txs/new?token=` is for BlockCypher tesnet, and the address `1JHMjL7V3heBZYieNcyHaqvy2aPA5fmY7S`  is a Bitcoin mainnet address.

* Unable to find a transaction to spend for address 1JHMjL7V3heBZYieNcyHaqvy2aPA5fmY7S -> Address `1JHMjL7V3heBZYieNcyHaqvy2aPA5fmY7S` has no balance.
* Error building transaction: Invalid output address: wrong network -> url for tesnnet, address mainet.
* Not enough funds after fees in 0 inputs to pay for 0 outputs -> Balance from inputs should include tx fee.
* Error validating generated transaction: Transaction missing input or output -> missing output?

Please paste here, code, and API request/reponse.

**Comment by misuqian** [comment]
hi.is there any api for create mainnet address transaction?
