### ISSUE TITLE
Ritiro bilanci

### ISSUE THREAD

**Issue by miccgiov** [blockcypher/php-client#36]
Buonasera vorrei cortesemente sapere come fare a ritirare i fondi rimasti in bilancio,chiedo scusa ma non riesco proprio a capirlo,sarà la mia età,ringrazio anticipatamente chi mi potrà essere di aiuto in questa mia richiesta.
Un saluto da Gianni

**Comment by josecelano** [comment]
Buonasera, non ho capito molto bene la domanda. Dove sono i fondi?. Se sono su uno delle indirizze da lei usato in qualche esempio, drová creare una nuova transazione per trasnferirli in un altro indirizzo oppure importare la chiave privata usando un altro wallet.

**Comment by miccgiov** [comment]
Chiedo nuovamente scusa per il mio disturbo,mi potrebbe dire i passaggi da fare? sa ho una certa età e non vorrei commettere errori,la prego cortesemente di comunicarmi i vari passa




----Messaggio originale----

Da: "Jose Celano" <notifications@github.com>

Data: 20/07/2017 18.32

A: "blockcypher/php-client"<php-client@noreply.github.com>

Cc: "miccgiov"<miccgiov@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [blockcypher/php-client] Ritiro bilanci (#36)




Buonasera, non ho capito molto bene la domanda. Dove sono i fondi?. Se sono su uno delle indirizze da lei usato in qualche esempio, drová creare una nuova transazione per trasnferirli in un altro indirizzo oppure importare la chiave privata usando un altro wallet.

**Comment by miccgiov** [comment]
Chiedo nuovamentescusa per il disturbo che potrei dare,il mio problema è che ho dei bilanci in attivo su dei conti sia bitcoin che litecoin,potrebbe cortesemente dirmi che passaggi dovrei fare in modo da poterli ritirare? sa ho una certa  età e non vorrei commettere errori e perdere le mie piccole somme,le sarei grato se potesse aiutarmi sul come eseguire le operazioni per poter ritirale o inviare ai miei portafogli.La ringrazio anticipatamente per l'aiuto che potrà darmi.Saluti Giovanni Miccoli





----Messaggio originale----

Da: "Jose Celano" <notifications@github.com>

Data: 20/07/2017 18.32

A: "blockcypher/php-client"<php-client@noreply.github.com>

Cc: "miccgiov"<miccgiov@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [blockcypher/php-client] Ritiro bilanci (#36)




Buonasera, non ho capito molto bene la domanda. Dove sono i fondi?. Se sono su uno delle indirizze da lei usato in qualche esempio, drová creare una nuova transazione per trasnferirli in un altro indirizzo oppure importare la chiave privata usando un altro wallet.

**Comment by miccgiov** [comment]
i fondi sono su blockcypher mi potrebbe aiutare a come eseguire i passaggi da lei spiegati non sono molto esperto ho 60 anni quindi sono sicuro di fare qualche sbaglio senza un aiuto di una persona preparata come lei grazie
