### ISSUE TITLE
bitwasp and mdanter

### ISSUE THREAD

**Issue by jda1586** [blockcypher/php-client#38]
I have installed version 1.5.0 of blockcypher/php-client
Mdanter version change to 0.4.2 but bitwasp 0.0.7.1 is not compatible with it so when blockcypher/php-client is installed in Laravel 5.4.x and you try to create a transaction it has this bug:

> **Class 'Mdanter\Ecc\Math\Gmp' not found in Math.php (line 8)**
> _PHP Fatal error: Class 'Mdanter\Ecc\Math\Gmp' not found in 
> _C:\ ......\vendor\bitwasp\bitcoin\src\Math\Math.php on line 8_

When installing bitwasp 0.0.7.1 the dependency requests "mdanter/ecc": "~0.3" so composer will install mdanter/ecc version 0.4.2. If I forced the installation of mdanter/ecc version 0.3.1 this incompatible with symfony/console v3.3.6

Any idea what I can do?

**Comment by rsbombard** [comment]
@jda1586  I'm having the exact same issue, actively trying to resolve it right now.

**Comment by rsbombard** [comment]
@jda1586 

I was able to get this working by forking https://github.com/phpecc/phpecc and bumping the symfony console version to 3.36 (https://github.com/rsbombard/phpecc/blob/bugfix/composer.json) and then aliasing the mdanter/ecc package in my composer.json. 

```javascript
 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/rsbombard/phpecc"
        }
    ],
    "require": {
        "php": ">=5.6.4",
        "blockcypher/php-client": "1.5.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "mdanter/ecc": "dev-bugfix as 0.3.0"
    }
```

Not exactly a good fix but at least it's working for now.

**Comment by jda1586** [comment]
Thank you. I will try this and back with the result

**Comment by josecelano** [comment]
Hi, that's an old TODO:

https://github.com/blockcypher/php-client/issues/14

I have to update to the latest version of `bitwasp/bitcoin` but there was a change in the API in a method we are using. I do not remmeber now what was the method but I think it was something related to the signature. You can run the tests to be sure your change does not break any feature. I hope I will have time soon to upgrade the package.

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
