### ISSUE TITLE
Error when requesting ether from faucet

### ISSUE THREAD

**Issue by ftppro** [blockcypher/php-client#40]
Instead of using the php-client, I am using the following code to request ether from the faucet:

```
	$csURL = "https://api.blockcypher.com/v1/beth/test/faucet?token={my token}";
	$sPostString = "address={my address}&amount=1000000000000000000";
	
	$ch = curl_init();    
	curl_setopt($ch, CURLOPT_URL, $csURL);  
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1); 
	curl_setopt($ch, CURLOPT_POSTFIELDS, $sPostString);
	$sResponse = curl_exec ($ch);     
	curl_close ($ch); 
	echo "#$sResponse#";
```

This returns the following message:
"Error decoding faucet info, invalid character 'a' looking for beginning of value."

My address and token have been verified by your other functions to be correct.

**Comment by alexeygon** [comment]
Try address without 0x
