### ISSUE TITLE
How to create transaction signature for blockcypher ethereum API

### ISSUE THREAD

**Issue by ftppro** [blockcypher/php-client#42]
The transaction signing process for the blockcypher ethereum API is explained here:
https://www.blockcypher.com/dev/ethereum/#creating-transactions

When their "addrs" endpoint is called, their API creates a new ethereum address, and a 64-character private key is provided. 

When their "/txs/new" endpoint is called, their API provides a "tosign" string which must be used with the 64-character private key, to produce a signature.

I need to know how to create that signature, which can be used with their "/txs/send" endpoint.

I do not wish to use their signer tool, because it requires that the GO programming language is installed on my server. If I get a new server, I don't want to have to reinstall a bunch of additional libraries.

I looked at the Bitwasp examples, and could not find a method that simply creates a transaction signature.

Please provide specific instructions which describe the simplest method to create a transaction signature for the blockcypher ethereum API.

**Comment by ar-to** [comment]
So I had this same problem and I made a [pull request](https://github.com/blockcypher/php-client/pull/66/files) to hopefully get this info added to the readme. I think this repo is not being checked very often because the travis test failed and the little response rate on these issues.

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
