### ISSUE TITLE
 Fatal error: Uncaught BlockCypher\Exception\BlockCypherSignatureException: 1 private keys do not correspond to any input. Please check private keys provided.

### ISSUE THREAD

**Issue by ShoaibSK** [blockcypher/php-client#45]
I am working on blockcypher create sign and send transaction example. I am able to create new transaction every time however when i am signing the transaction i am getting following error.

Fatal error: Uncaught BlockCypher\Exception\BlockCypherSignatureException: 1 private keys do not correspond to any input. Please check private keys provided. in C:\xampp_new\htdocs\opaldemoareabit\Blockcypher\blockcypher\php-client\lib\BlockCypher\Api\TXSkeleton.php:164 Stack trace: #0 C:\xampp_new\htdocs\opaldemoareabit\Blockcypher\blockcypher\php-client\lib\BlockCypher\Api\TXSkeleton.php(102): BlockCypher\Api\TXSkeleton->generateSignatures(Object(BlockCypher\Crypto\PrivateKeyList), Object(BlockCypher\Crypto\PrivateKeyList), 'btc-testnet') #1 C:\xampp_new\htdocs\opaldemoareabit\Blockcypher\blockcypher\php-client\lib\BlockCypher\Client\TXClient.php(35): BlockCypher\Api\TXSkeleton->sign(Array, 'btc-testnet') #2 C:\xampp_new\htdocs\opaldemoareabit\action\bitcoin_wallet.php(56): BlockCypher\Client\TXClient->sign(Object(BlockCypher\Api\TXSkeleton), Array) #3 C:\xampp_new\htdocs\opaldemoareabit\btcwallet.php(23): require_once('C:\\xampp_new\\ht...') #4 {main} thrown in C:\xampp_new\htdocs\opaldemoareabit\Blockcypher\blockcypher\php-client\lib\BlockCypher\Api\TXSkeleton.php on line 164

The private key which i am passing is from generateAddress api call. I'd searched a lot to solve this issue but didn't found any help. Please let me know the problem i am stuck with this issue from last 2 days

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
