### ISSUE TITLE
Class 'Mdanter\Ecc\\Math\Gmp' not found

### ISSUE THREAD

**Issue by sachin-lalaworld** [blockcypher/php-client#46]

**Comment by ofumbi** [comment]
I also have this problem. Have you got a solution? because I had to mess up my dependencies to make it work .  Its a problem in bitwasp/boitcoin 0.0.7.*  You remove blockcypher and install bitwasp/bitcoin dev-master. it works fine. Problem is now You don't have blockcypher.

**Comment by sachin-lalaworld** [comment]
@ofumbi Yes I have got solution. Don't remove blockcypher. Please follow the following steps:

1. Install blockcypher using composer 
composer require blockcypher/php-client

2. Then add following content in composer.json
"require": {
"mdanter/ecc": "dev-bugfix as 0.3.0"
}

3. Then run composer update command on terminal.

**Comment by ofumbi** [comment]
@sachin-lalaworld  Thanks.  it works now

**Comment by oyepez003** [comment]
@sachin-lalaworld Today I got the next error:

  Problem 1
    - bitwasp/buffertools v0.4.1 requires mdanter/ecc ~0.4 -> satisfiable by mda
nter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.5.0] but these co
nflict with your requirements or minimum-stability.
    - bitwasp/buffertools v0.4.1 requires mdanter/ecc ~0.4 -> satisfiable by mda
nter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.5.0] but these co
nflict with your requirements or minimum-stability.
    - bitwasp/buffertools v0.4.1 requires mdanter/ecc ~0.4 -> satisfiable by mda
nter/ecc[0.4.x-dev, v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.5.0] but these co
nflict with your requirements or minimum-stability.
    - Installation request for bitwasp/buffertools (locked at v0.4.1) -> satisfi
able by bitwasp/buffertools[v0.4.1].

The bitwasp/buffertools is using the ~0.4 and is not satisfiable by 0.3.x...

This library if full out of date...

**Comment by ofumbi** [comment]
Oh I got a better solutiuon
composer require "bitwasp/bitcoin":"dev-master as 0.0.7.x-dev",

**Comment by oyepez003** [comment]
Nice solution, you can send me how to create and sign the transaction using bitwsap. The signer of php-client is the problem with my current project dependencies...

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
