### ISSUE TITLE
Error while doing transaction dynamically : {"error": "Couldn't deserialize request: math/big: cannot unmarshal "\"1000\"" into a *big.Int"}

### ISSUE THREAD

**Issue by Govind13100** [blockcypher/php-client#49]
{"error": "Couldn't deserialize request: math/big: cannot unmarshal "\"1000\"" into a *big.Int"}

I tried curl with POST and GET both but for amount it is returning the above error, please help me if anyone can. I am stuck into this from last 1 day.

**Comment by iamdevesin** [comment]
Stuck here too... try using the sample i transaction-api

I used that to create transaction for BTC but it is not going for ETH

Perhaps i'm missing endpoint or something

Anyone that solved this  should please help

**Comment by Govind13100** [comment]
You cannot use same(btc) library for ETH. Just use raw url , hit them buy curl and sign the transaction.Everything is given in their doc. I have also done the same for ETH

**Comment by Govind13100** [comment]
{"error": "Couldn't deserialize request: math/big: cannot unmarshal ""1000"" into a *big.Int"}
 

For this you have to deal with satoshi for ex if you want to send 0.1 btc then in parameter you have to multiply 0.1 * 100000000(satoshi) for ETH it’s 18 times zero. Min amount of btc to transfer is 0.00001. I hope that could help. I solved my same issue by this.

**Comment by iamdevesin** [comment]
Thanks @Govind13100 , I tried parsing the ETH transaction using PHP curl but so far, no luck

Here's what I've tried

				<?php
				$curl = curl_init();
				curl_setopt_array($curl, array(
				  CURLOPT_URL => "https://api.blockcypher.com/v1/eth/main/txs/new?token=mytoken?inputs=add42af7dd58b27e1e6ca5c4fdc01214b52d382f?outputs=884bae20ee442a1d53a1d44b1067af42f896e541?value=4200000000000000",
				  CURLOPT_RETURNTRANSFER => true,
				  CURLOPT_ENCODING => "",
				  CURLOPT_MAXREDIRS => 10,
				  CURLOPT_TIMEOUT => 30,
				  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
				  CURLOPT_CUSTOMREQUEST => "POST",
				  CURLOPT_SSL_VERIFYHOST =>0,
				  CURLOPT_SSL_VERIFYPEER =>0,
				));
				echo $response = curl_exec($curl);
				echo $err = curl_error($curl);
				curl_close($curl);
				?>

Can you please provide a sample snippet for creating ETH transaction with curl or check what's wrong with my request?

thank you

**Comment by Govind13100** [comment]
```
$from = $_GET['f_address'];
$to = $_GET['t_address'];
$at = $_GET['amount'] * 100000000000000000;

$p_key = $_GET['p_key'];

$amount = sprintf('%f', (float)$at);

$ao = intval($amount);


$trade_data = '{"inputs":[{"addresses": ["'.$from.'"]}],"outputs":[{"addresses": ["'.$to.'"], "value": '.$ao.'}]}';

$url = 'https://api.blockcypher.com/v1/beth/test/txs/new?token=de45b2d4ed17475aadef7ea6ceaa0f8e';

$args = array(
             'method' => 'POST',
             'timeout' => 10,
             'redirection' => 5,
             'httpversion' => '1.1',
             'user-agent' => 'WordPress/version;URL',
             'reject_unsafe_urls' => false,
             'blocking' => true,
             'headers' => array('Content-Type' => 'application/json'),
             'cookies' => array(),
             'body' => $trade_data,
             'compress' => false,
             'decompress' => true,
             'sslverify' => true,
             'stream' => false,
             'filename' => null,
             'limit_response_size' => null,
            );




$a = wp_remote_post($url,$args);
//echo "<pre>";
//print_r($a);
//die;

if($a['response']['code'] == 201){
    
    
    $body = $a['body'];
  
    $tosigns = json_decode($body,true);
    
    $tosign = $tosigns['tosign'][0];
    
    // sign the transaction
    $sign = file_get_contents(get_site_url().'/BitcoinECDSA.php/test.php?h='.$tosign.'&p_key='.$p_key);
    
    // make array of sign return in pervious step 
    $signature = array('signatures' => array($sign));
   
    // merge tx & signature 
    $data = array_merge($tosigns,$signature);
    
    // make json of data
    $json_data = json_encode($data);
    
    // confirm the transaction
    $url = 'https://api.blockcypher.com/v1/beth/test/txs/send?token=de45b2d4ed17475aadef7ea6ceaa0f8e';
    
    $args = array(
                 'method' => 'POST',
                 'timeout' => 10,
                 'redirection' => 5,
                 'httpversion' => '1.1',
                 'user-agent' => 'WordPress/version;URL',
                 'reject_unsafe_urls' => false,
                 'blocking' => true,
                 'headers' => array('Content-Type' => 'application/json'),
                 'cookies' => array(),
                 'body' => $json_data,
                 'compress' => false,
                 'decompress' => true,
                 'sslverify' => true,
                 'stream' => false,
                 'filename' => null,
                 'limit_response_size' => null,
                );

    
    
    
    $tx = wp_remote_post($url,$args);
//    echo "<pre>";
//    print_r($tx);
    $body = $tx['body'];
    
    $decode_body = json_decode($body,true);

    echo $tx_hash = $decode_body['tx']['hash'];
   if($body == ''){
       echo 0;
   }
 
    
   // echo $tx_fees = $decode_body['tx']['fees'];
    

    
}else{
   
    //print_r($a['body']);
    
    echo 0;
    
    
}
```

**Comment by Insano41** [comment]
@Govind13100 I have problem with sign transaction. Do you customized BitcoinECDSA for Ethereum?

I get this error "Could not compute an address from provided signature: invalid transaction v, r, s values."

When I sign transaction with https://github.com/blockcypher/btcutils/tree/master/signer It works, but I need to do it in PHP.

Thanks.

**Comment by alexey-p** [comment]
{"error": "Couldn't deserialize request: math/big: cannot unmarshal ""1000"" into a *big.Int"}


The problem is that you pass STRING. **You should pass float or int.**

**Comment by hai-ru** [comment]
I want to transfer 1963100010400.0002 stoshi doge but I'd return error message.

{"error": "Couldn't deserialize request: math/big: cannot unmarshal "1963100010400.0002" into a *big.Int"}"
