### ISSUE TITLE
Got Http response code 400

### ISSUE THREAD

**Issue by UpalChakraborty** [blockcypher/php-client#5]
When I am trying to create transaction, I am getting the following error.

Got Http response code 400 when accessing https://api.blockcypher.com/v1/btc/main/txs/new?token=xxxx.

I was trying to run the following code for BTC.main with mainnet bitcoin addresses.

http://blockcypher.github.io/php-client/sample/doc/transaction-api/CreateTransaction.html

**Comment by josecelano** [comment]
Hi @UpalChakraborty. You should get an error message in the response body. Something like this:

```
{
    "errors": [
        {
            "error": "Unable to find a transaction to spend for address n3D2YXwvpoPg8FhcWpzJiS3SvKKGD8AXZ4."
        },
        {
            "error": "Error building transaction: Invalid output address: wrong network.."
        },
        {
            "error": "Not enough funds after fees in 0 inputs to pay for 0 outputs, missing -2600."
        },
        {
            "error": "Error validating generated transaction: Transaction missing input or output."
        }
    ],
    "tx": {
         ...
    }
}
```

If you have log enabled you can see the response body there.

**Comment by UpalChakraborty** [comment]
@josecelano Yes. The error message in response body is something like this. How do I fix this ?

**Comment by josecelano** [comment]
Could you please paste the exact error message here?. You can remove addresses. 

The first error:

`"Unable to find a transaction to spend for address"`

means you do not have enought balance in your source address, so you need to fund that address.

The second error:

`"Error building transaction: Invalid output address: wrong network.."´

means you are not using a rigth address for the network you have selected, in yout case mainnet.

You can use the blockchain explorer: https://live.blockcypher.com/ to get address balance or any other info.

**Comment by UpalChakraborty** [comment]
```
"errors": [
        {
            "error": "Unable to find a transaction to spend for address 1xxx."
        },
        {
            "error": "Not enough funds in 0 inputs to pay for 1 outputs, missing -100000."
        },
        {
            "error": "Not enough funds after fees in 0 inputs to pay for 1 outputs, missing -104400."
        },
        {
            "error": "Error validating generated transaction: Transaction missing input or output."
        }
    ]
```
According to https://live.blockcypher.com/ 1xxx balance is 0.003901 BTC.

**Comment by josecelano** [comment]
The first error occurs when you do not have enought funds in the input addresses for paying the output plus the fees.

The second error means you are using a private key which not correspond with any of the input addresses. This could happen if you are not using the rigth private key or even if you are passing more private keys than input addresses. Library only allows not compressed private keys (HEX).

**Comment by UpalChakraborty** [comment]
@josecelano In case of the first error, the address still have funds. It seems blockcypher server is rejecting continuous requests with same and hence throwing 400. In any case, it is not a big problem anymore.

But, the second error is not because of wrong private key. I have provided correct private key, but it is still happening. This issue is also mentioned on stackoverflow - http://bitcoin.stackexchange.com/questions/42239/why-blockcypher-send-transaction-is-throwing-fatal-error.

**Comment by josecelano** [comment]
@UpalChakraborty I am going to try to reproduce the problem but that exception is only throw is this line:

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Api/TXSkeleton.php#L148

What the method `generateSignatures` does is basically iterate over all input addresses and use the private key of each address to sign the transaction. When a private key is not used becasue the address of that key is not present in the inputs the method throws an exception becuase the user has passed a private key not needed.

You can do a `var_dump` on line:

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Api/TXSkeleton.php#L146

for `$privateKeyList` and `$privateKeysUsed`. `$privateKeysUsed` should content all your inputs addresses and `$privateKeyList` the list of private keys for them.

Maybe this way you can find out what is not working.

**Comment by josecelano** [comment]
Hi @UpalChakraborty can I close this issue?. It seems the problem was caused becasue the php-client is not supporting umcompressed public keys. Can you confirm it?

**Comment by UpalChakraborty** [comment]
Yes. The issue was caused by uncompressed public keys. Thank you so much for your help. Closing this issue now.

**Comment by cis-s** [comment]
Hello I am using BlockCypher API and I am getting below error - 
{'error': 'Error building faucet transaction: Not enough funds in 0 inputs to pay for 1 outputs, missing -100}
when I am trying to use send_faucet_coins method to add faucet coins to btc address. 

Kindly help !!
