### ISSUE TITLE
Where is $apiContexts located?

### ISSUE THREAD

**Issue by forddyce** [blockcypher/php-client#50]
Tried your example at http://blockcypher.github.io/php-client/sample/doc/address-api/GenerateAddress.html

Just realized `$apiContexts` need to be created first. In your example it is an array:

```
require __DIR__ . '/../bootstrap.php';

$addressClient = new \BlockCypher\Client\AddressClient($apiContexts['BTC.main']);

try {
    $addressKeyChain = $addressClient->generateAddress();
} catch (Exception $ex) {
    ResultPrinter::printError("Generate Address", "AddressKeyChain", null, null, $ex);
    exit(1);
}

ResultPrinter::printResult("Generate Address", "AddressKeyChain", $addressKeyChain->getAddress(), null, $addressKeyChain);

return $addressKeyChain;

```

Where can I find your `$apiContexts` ?

**Comment by forddyce** [comment]
And by the way I installed it via composer. `\BlockCypher\Client\AddressClient` class not found, in fact the Client folder does not even exists.

**Comment by josecelano** [comment]
$apiContexts are created in the bootstrap file:

https://github.com/blockcypher/php-client/blob/master/sample/bootstrap.php#L106

You can also use a config file. More info in the wiki:

https://github.com/blockcypher/php-client/wiki

Regarding your class not found error you probably are using an old client version. YOu should use the lastest release:

https://github.com/blockcypher/php-client/releases/latest
