### ISSUE TITLE
Class 'Mdanter\Ecc\Math\Gmp' not found

### ISSUE THREAD

**Issue by oyepez003** [blockcypher/php-client#54]
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Mdanter\Ecc\Math\Gmp' not found

Error with the latest version of blockcypher...

**Comment by InspiredPrynce** [comment]
Someone should please fix this!

**Comment by TokiSeven** [comment]
Have this error too. Does anyone know how to fix it?

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
