### ISSUE TITLE
error in sign-in at Create Transaction 

### ISSUE THREAD

**Issue by pixelgaurav** [blockcypher/php-client#63]
FatalThrowableError in PrivateKeyList.php line 54:
Type error: Argument 1 passed to BlockCypher\Crypto\PrivateKeyList::addPrivateKey() must be an instance of BitWasp\Bitcoin\Key\PrivateKeyInterface, instance of BitWasp\Bitcoin\Crypto\EcAdapter\Impl\PhpEcc\Key\PrivateKey given, called in /home/pixel/Documents/tests/vendor/blockcypher/php-client/lib/BlockCypher/Crypto/PrivateKeyList.php on line 43

here is code 
  public function addPrivateKey(PrivateKeyInterface $privateKey)
    {
        $pubKeyHex = $privateKey->getPublicKey()->getHex();
        $this->privateKeys[$pubKeyHex] = $privateKey;
    }

**Comment by ar-to** [comment]
Had the same problem when signing a bitcoin transaction. The problem has to do with the interface file its expecting has been moved and renamed inside the bitWasp library.
from: 
`use BitWasp\Bitcoin\Key\PrivateKeyInterface;`
to: 
`use BitWasp\Bitcoin\Crypto\EcAdapter\Key\PrivateKeyInterface;`
Changing this inside the BlockCypher\Crypto\PrivateKeyList.php file will fix this problem as long as you do not update `blockcypher/php-client` or reinstall with composer. This is not ideal of course. I made a pull request for this but the only solution I can think of is forking the main repo, creating a branch for the change and adding it to your composer.json as a dependancy (a bit complicated but composer explains this in their docs) or just symlink into the vendor folder but you have to ensure this is done correctly too. Good luck

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
