### ISSUE TITLE
PHP 7.1 mcrypt not there anymore, package uninstallable

### ISSUE THREAD

**Issue by dib258** [blockcypher/php-client#67]
Hi,

I wanted to install the package to Laravel but I have the following error : 

    - bitwasp/bitcoin v0.0.7.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - bitwasp/bitcoin v0.0.7 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - blockcypher/php-client v1.5.0 requires bitwasp/bitcoin 0.0.7.* -> satisfiable by bitwasp/bitcoin[v0.0.7, v0.0.7.1].
    - Installation request for blockcypher/php-client ^1.5 -> satisfiable by blockcypher/php-client[v1.5.0].

This is not related to Laravel but rather the version of PHP 7.1 which doesn't have anymore the extension mcrypt. What can I do to use the package ? Do I need to wait an update ?

Thanks in advance for you help

**Comment by AvionicsBird** [comment]
Issue still exist.. Whats the solution?

**Comment by quentinlesceller** [comment]
FIxed in #111. Try using v2.0.0-beta.1 and please report back. Thank you!
