### ISSUE TITLE
CreateAndSignAndSendTransaction shows error

### ISSUE THREAD

**Issue by subhasaha** [blockcypher/php-client#7]
In CreateAndSignAndSendTransaction the request and response is generated, but it shows the following error.

Fatal error: Uncaught exception 'BlockCypher\Exception\BlockCypherSignatureException' with message '1 private keys do not correspond to any input. Please check private keys provided.' in /myserver/blockcypher1/php-client/blockcypher/php-client/lib/BlockCypher/Api/TXSkeleton.php:148 Stack trace: #0 /myserver/blockcypher1/php-client/blockcypher/php-client/lib/BlockCypher/Api/TXSkeleton.php(96): BlockCypher\Api\TXSkeleton->generateSignatures(Object(BlockCypher\Crypto\PrivateKeyList), 'btc') #1 /myserver/blockcypher1/php-client/blockcypher/php-client/lib/BlockCypher/Client/TXClient.php(35): BlockCypher\Api\TXSkeleton->sign(Array, 'btc') #2 /myserver/blockcypher1/php-client/blockcypher/php-client/sample/transaction-api/CreateAndSignAndSendTransaction.php(32): BlockCypher\Client\TXClient->sign(Object(BlockCypher\Api\TXSkeleton), Array) #3 {main} thrown in /myserver/blockcypher1/php-client/blockcypher/php-client/lib/BlockCypher/Api/TXSkeleton.php on line 148

Please help.

**Comment by josecelano** [comment]
Hi @subhasaha It could be the same problem reported here: 

https://github.com/blockcypher/php-client/issues/5

The php-client does not support uncompressed public keys, that could be the problem.

**Comment by subhasaha** [comment]
So what can we do as a solution because I am stuck here for a lot of days :)

**Comment by josecelano** [comment]
@subhasaha If you are using the BlocCypher API to generate the address you get the private key, the compressed public key and the bitcoin address, so you should not have problem.

If you are using another library, it depends. Probably you have an option/setting, etc. to use compressed public keys.

But we should confirm that is your case. Could you send me a sample address (private and public key) generated with the library you are using now?

**Comment by subhasaha** [comment]
Thank you for ur help.
