### ISSUE TITLE
Transaction to multiple address

### ISSUE THREAD

**Issue by emabusi** [blockcypher/php-client#72]
How do initiate a transaction (send btc). Example with 110000 satoshi send 60000 to address x and 40000 to address y, and the remainder as transaction fee.

**Comment by ptcrank** [comment]
$tx = new \BlockCypher\Api\TX();

/// Tx inputs
$input = new \BlockCypher\Api\TXInput();
$input->addAddress("INPUT ADDRESS");  //Minimum inventory of more than 10,000 Satoshi
```
// Tx outputs
$outputx = new \BlockCypher\Api\TXOutput();
$outputx->addAddress("x");  // OUTPUT ADDRESS x
$outputx->setValue(60000);

$outputy = new \BlockCypher\Api\TXOutput();
$outputy->addAddress("y");  // OUTPUT ADDRESS y
$outputy->setValue(40000);

// Tx
$tx = new \BlockCypher\Api\TX();
$tx->addInput($input);
$tx->addOutput($outputx);
$tx->addOutput($outputy);
```
