### ISSUE TITLE
Example for the PaymentForwardCallback object

### ISSUE THREAD

**Issue by lucastruong** [blockcypher/php-client#74]
I read the PaymentForwardCallback object. But I cannot see anything about an example for this.
Pls help me.

Ref. https://www.blockcypher.com/dev/bitcoin/#create-payment-endpoint
> If you decide to have a callback_url, you’ll receive a payload at that url whenever a payment is made to the input_address. The payload will come in the form of a PaymentForwardCallback object.

**Comment by dzona** [comment]
see #74
