### ISSUE TITLE
Uncaught BlockCypher\Exception\BlockCypherInvalidPrivateKeyException: Invalid private key format, hex expected.Please install GMP extension.

### ISSUE THREAD

**Issue by MadhuriMhavarkar** [blockcypher/php-client#77]
I am trying to create, sign and send transaction from blockcypher's sample files.

But it throws an error 

Fatal error: Uncaught BlockCypher\Exception\BlockCypherInvalidPrivateKeyException: Invalid private key format, hex expected.Please install GMP extension. in /opt/lampp/htdocs/bitiagowallet/php-client/blockcypher/php-client/lib/BlockCypher/Crypto/PrivateKeyManipulator.php:86 Stack trace: #0 /opt/lampp/htdocs/bitiagowallet/php-client/blockcypher/php-client/lib/BlockCypher/Crypto/PrivateKeyList.php(40): BlockCypher\Crypto\PrivateKeyManipulator::importPrivateKeyFromHex('032e958aed962d2...', true) #1 /opt/lampp/htdocs/bitiagowallet/php-client/blockcypher/php-client/lib/BlockCypher/Api/TXSkeleton.php(95): BlockCypher\Crypto\PrivateKeyList::fromHexPrivateKeyArray(Array, 'btc', true) #2 /opt/lampp/htdocs/bitiagowallet/php-client/blockcypher/php-client/lib/BlockCypher/Client/TXClient.php(35): BlockCypher\Api\TXSkeleton->sign(Array, 'btc') #3 /opt/lampp/htdocs/bitiagowallet/php-client/blockcypher/php-client/sample/transaction-api/CreateAndSignAndSendTransaction.php(31): BlockCypher\Client\TXClient->sign(Object(BlockCypher\Api\TXSke in /opt/lampp/htdocs/bitiagowallet/php-client/blockcypher/php-client/lib/BlockCypher/Crypto/PrivateKeyManipulator.php on line 86

I've given the private key to sign transaction returned by generate address endpoint.

Then why it's still giving such error... I can not figure it out... can anyone give the solution for this.?? 

Regards,
Madhuri

**Comment by quentinlesceller** [comment]
Fixed in #111.
