### ISSUE TITLE
address unsuported

### ISSUE THREAD

**Issue by yura-sutnuk** [blockcypher/php-client#78]
Hi, i have error when i try to get address info (http://api.blockcypher.com/v1/eth/main/addrs/d1fe40d9d15da8b9686444179357054f36159cac) i get {"error": "Address not found or unsupported: d1fe40d9d15da8b9686444179357054f36159cac"} but this address is exists and even have real transactions (https://etherscan.io/address/0xd1fe40d9d15da8b9686444179357054f36159cac), could you help with this error?

**Comment by quentinlesceller** [comment]
Looks fixed.
