### ISSUE TITLE
How can I fetch attribute of the Callback URL

### ISSUE THREAD

**Issue by moinrazakhan** [blockcypher/php-client#79]
Callback url triggered well, but i can't fetch any attribute like its value ,input address etc., i can't fetch the attribute on the POST value as well, Can you please suggest how can i fetch that attribute? I does not get below screen shot attribute value.

![image](https://user-images.githubusercontent.com/8957458/45640859-6e85e500-bad1-11e8-865c-a53dc6116011.png)

**Comment by dzona** [comment]
you may try creating postback object, in your case `PaymentForward`, from payload.

```
$payload = file_get_contents('php://input');
$attributes = json_decode($payload);

$paymentFw = new PaymentForward($attributes);
echo $paymentFw->getValue();
```

or access it directly from array

```
$payload = file_get_contents('php://input');
$attributes = json_decode($payload);

echo $attributes['value'];
```
