### ISSUE TITLE
Couldn't deserialize request

### ISSUE THREAD

**Issue by yura-sutnuk** [blockcypher/php-client#81]
Hi, when i trying to send more then 9eth i get error 

`Couldn't deserialize request: math/big: cannot unmarshal "1.1E+21" into a *big.Int`

i think it is becouse the amount in WEI that i trying to send is biger then PHP_INT_MAX but if I try to break a transaction into several outputs i get 

`"error": "Missing output or too many outputs, Ethereum transactions take exactly one.`

How can i send for example 11 eth to someone?

**Comment by cooljar** [comment]
Hi, do you already slove this issue, i have same problem.

**Comment by yura-sutnuk** [comment]
Yes, the problem was that after I got the SKELETON transaction, I use the json_decode function to convert json to an array, and at that moment the transaction value is not converted correctly and looks like 1.1E+21. 
Solution: it is durty but I worked with Json, as with a string so as not to transform into an array or object
