### ISSUE TITLE
Missing Accessor: BlockCypher\Api\TX:setBlockIndex

### ISSUE THREAD

**Issue by techgardeners** [blockcypher/php-client#82]
On my log I have always this warning
BlockCypher\Validation\ModelAccessorValidator: DEBUG	: Missing Accessor: BlockCypher\Api\TX:setBlockIndex. You might be using older version of SDK. If not, create an issue

So I created a Issue

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
