### ISSUE TITLE
Spend non-native segwit (P2SH-P2WPKH)?

### ISSUE THREAD

**Issue by sbtc1** [blockcypher/php-client#85]
Hi

Does the API support spending from a P2SH address (3.......) that is not multisig but a P2SH-P2WPKH address?
The documentation only covers script-type multisg-n-of-m for P2SH addresses. Is this a known gap, or can it be achieved through another script-type or other method?

(It looks like the API now expects multisig when the address starts with a 3)

kind regards

**Comment by quentinlesceller** [comment]
Now it does :). See [our new blog post](https://blog.blockcypher.com/a-guide-to-blockcyphers-new-bech32-features-4aa33baeaf51?source=collection_home---5------0-----------------------)  for more info.
