### ISSUE TITLE
Formatting error on "File based configurations" instructions

### ISSUE THREAD

**Issue by toneloc** [blockcypher/php-client#9]
```
$webhook->setUrl("https://requestb.in/slmm49sl?uniqid=" . uniqid());
$webhook->setEvent('unconfirmed-tx');
```

'webhook' should be 'webHook'

**Comment by josecelano** [comment]
Hi @toneloc I can not find the file containing that code:

https://github.com/blockcypher/php-client/search?utf8=%E2%9C%93&q=%24webhook-%3EsetEvent%28%27unconfirmed-tx%27%29%3B

**Comment by josecelano** [comment]
OK sorry @toneloc I have found in the wiki:

https://github.com/blockcypher/php-client/wiki/File-based-Configurations

Thanks.

**Comment by josecelano** [comment]
Fixed, FYI you have more docs in: http://dev.blockcypher.com/?php#
