### ISSUE TITLE
Getter function for 'tx' in 'BlockCypher\Api\TXSkeleton' class should have a proper return type.

### ISSUE THREAD

**Issue by harwinder-developer** [blockcypher/php-client#93]
Hi, 
i am getting this error when i try to run my /sample/transaction-api/CreateAndSignAndSendTransactionBCTesnet.php . It was working fine before 2 days , but today it is throwing this error donot know why , can you please help me to solve this things. 

Thanks

**Comment by quentinlesceller** [comment]
Try using v2.0.0-beta.1 and please report back. Thank you!
