### ISSUE TITLE
Usage of removed libraries - library no longer installable

### ISSUE THREAD

**Issue by nestormata** [blockcypher/php-client#94]
Installing this library is no longer possible.
Because this library depends on bitwasp/bitcoin v0.0.7 (a very old version btw) and that library requires the library rgooding/protobuf-php which was removed completely.

Can you guys please update the library so it can be used again? Or then declare it non functional so, somone else can take over or something?

Thanks

**Comment by jingyao97** [comment]
Yeah, there is an error right now. Should i actually just remove it from the composer.lock?

**Comment by itsnotyoutoday** [comment]
I'm currently working on a fork of this library at https://github.com/itsnotyoutoday/php-client/tree/phpmodernization ..  Everything passed with PHPUnit 4, but when I found out travis-ci uses modern day PHPUnit 8.3.4 I had to start rewriting all the tests.. If anyone feels like contributing to this fork to fix the tests that'd be awesome.

**Comment by olegdev01** [comment]
Same issue for me.

**Comment by quentinlesceller** [comment]
Done in #111.
