### ISSUE TITLE
Error while sending raw TX

### ISSUE THREAD

**Issue by maxspb89** [blockcypher/php-client#96]
Trying to send a raw transaction, formed by my code to network. For example: 
`curl -d '{"tx":"01000000016313abc16661afc8dd7ea5ae608c660fdf1fb3a9760d95b36823d673e717b5b2010000008b483045022100c9fceded42846480d9219f062e98af1b69cadee5032ae42cf0e6fb2d7e1f5c920220565771eb9c343a1d34b1c462c0877906c1782749772f31ba0d137fdc5a6124c701410428a082067ef24fa90302fd7ac2001328c3ac255d8c94b47ce8048455701b53d895f55841bb27da12c8f1bd8e893da5bbd15e5d9b2df759e1a0820e146ce59065ffffffff0210270000000000001976a914ac0895e203f13ad4f88f44c949c7d40179bf60fd88acbd5e0000000000001976a914bdd65edb85a51bfeeb2dd5a53045b68349e8e68588ac00000000"}' https://api.blockcypher.com/v1/bcy/test/txs/push?token=***`

And getting the error` {"error": "Error validating transaction: Transaction 1d8ec538c63760e73c97a1e38da6e1cfc8bc46f36b5b7fd2974f510433e13d15 orphaned, missing reference b2b517e773d62368b3950d76a9b31fdf0f668c60aea57eddc8af6166c1ab1363."}`

When I send this transaction by browser at [BlockCypher](https://live.blockcypher.com/btc/pushtx/) it works fine (tested a couple of times). Also when I decode a transaction by API it returns no errors.

Please, help, whats going on? Is it matter that my plan is free?

**Comment by quentinlesceller** [comment]
Closing this issue since it's not related to the PHP Client.
